# Generated by Django 5.2.8 on 2026-01-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensordata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
